### PR TITLE
Auto init non-git repository (part 2)

### PR DESCRIPTION
**Pull request by mittalyashu**
Part 1 of this feature is #3596

### CODE REVIEW

**Comment by mittalyashu** [comment]
@KaKi87 can you take a look at this PR?

**Comment by KaKi87** [comment]
It seems okay. Is there a problem ?

**Comment by mittalyashu** [comment]
The code is not working 😅

**Comment by KaKi87** [comment]
Oh ! 😅 Hum, I'll check it out ASAP and keep you posted. ^^

**Comment by mittalyashu** [comment]
Thanks

**Comment by mittalyashu** [comment]
Closing this PR against #3599

**Pull request closed without merging**
