### PR TITLE
NodeGit + SQLite migration : implement clone feature

### PR DESCRIPTION
**Pull request by KaKi87**
The purpose of this PR is to replace the old simple-git/localStorage code by the new nodegit/sqlite methods to perforn a git clone using [NodeGIt's API](https://www.nodegit.org/api/clone/) and the [addRepository mixin](https://github.com/gitthermal/thermal/blob/chore/add-nodegit/src/renderer/mixins/addRepository.js).

### CODE REVIEW

**Comment by mittalyashu** [comment]
@KaKi87 Can you update the description of the PR?

**Comment by KaKi87** [comment]
Done, but there's not much to say.

**Comment by mittalyashu** [comment]
Progress bar is also a part of the clone repository feature, shows the progress of the clone repository which is very helpful especially for larger size repositories.

image

**Comment by mittalyashu** [comment]
Clone repository feature is working smoothly, can you run ESLint and format the code.

After then the PR is good to be merged.

**Comment by KaKi87** [comment]
Done.

**Comment by mittalyashu** [comment]
Awesome.

**Pull request merged**
